#!/bin/bash

set -e

REMOTE=${REMOTE:-origin}
GITHUB_CLI=${GITHUB_CLI:-gh}

branch=$1
[[ -n $branch ]] && [[ -z $(git branch | cut -b 3- | grep ^$branch$) ]] && echo git branch $branch does not exist && exit 1

remote_branch=$REMOTE/$branch

issue=$(echo $branch | sed -e 's/^\([a-z]\+-[0-9]\+\)-.*$/\1/')
[[ -z $issue ]] && echo branch $branch does not contain an issue number && exit 1

[[ -z $(git branch -a | cut -b 3- | grep ^remotes/$remote_branch$) ]] && echo git branch remotes/$remote_branch does not exist && exit 1

[[ $(git log $branch -1 --format="%h") = $(git log $branch -1 --format="%h") ]] || echo git branches $branch and $remote_branch do not point to the same commit || exit 1

[[ -z $(git log $branch -1 --grep="\\b$issue\\b" -i) ]] && echo commit description does not contain issue number && exit 1

subject=$(git log $branch -1 --format="%s")

pr=$($GITHUB_CLI pr list -H $branch | cut -f 1)
[[ -n $pr ]] && echo pr $pr already exists for branch $branch && exit 1

reviewers=$2
[[ -n $reviewers ]] && reviewers="-r $reviewers"

repo=$(git remote show $REMOTE | grep "Push\\s\\+URL:" | sed -e 's/^.*\.com:\([^\/]\+\).*/\1/')

echo "set -e"
echo "$GITHUB_CLI pr create -t \"$subject\" -H $repo:$branch -a '@me' $reviewers -d -F - <<\\BODY"
git ghj-print-pr-desc $branch
echo "BODY"
