#!/bin/bash

set -e

REMOTE=${REMOTE:-origin}
GITHUB_CLI=${GITHUB_CLI:-gh}

branch=$1
[[ -n $branch ]] && [[ -z $(git branch | cut -b 3- | grep ^$branch$) ]] && echo git branch $branch does not exist && exit 1

remote_branch_count=$2

remote_branch=$REMOTE/$branch

issue=$(echo $branch | sed -e 's/^\([a-z]\+-[0-9]\+\)-.*$/\1/')
[[ -z $issue ]] && echo branch $branch does not contain an issue number && exit 1

[[ -z $(git branch -a | cut -b 3- | grep ^remotes/$remote_branch$) ]] && echo git branch remotes/$remote_branch does not exist && exit 1

commit=$(git log $branch -1 --format="%h")

pr=$($GITHUB_CLI pr list -H $branch | cut -f 1)
[[ -z $pr ]] && echo branch $branch does not have a pr && exit 1

branch_count=$(git count-commits $branch)
[[ -z $remote_branch_count ]] && remote_branch_count=$branch_count

echo "set -e"
echo ""
echo "git push $REMOTE $branch --force-with-lease"
echo ""
echo "$GITHUB_CLI pr comment $pr -F - <<\\BODY"
echo "Changelog for $commit"
echo "- "
echo ""
echo "<details>"
echo "<summary>range diff</summary>"
echo ""
echo '```'
git range-diff $remote_branch~$remote_branch_count..$remote_branch $branch~$branch_count..$branch
echo '```'
echo "BODY"

subject=$(gh pr view $pr --json title -q '.title')

echo ""
echo "$GITHUB_CLI pr edit $pr -t \"$subject\" -F - <<\\BODY"
gh pr view $pr --json body -q '.body' | git ghj-print-pr-desc $branch -
echo "BODY"
