#!/bin/bash

set -e

branch=$1
[[ -n $branch ]] && [[ -z $(git branch | cut -b 3- | grep ^$branch$) ]] && echo git branch $branch does not exist && exit 1

issue=$(echo $branch | sed -e 's/^gh-\([0-9]\+\)-.*$/\1/')
[[ -z $issue ]] && echo branch $branch does not contain an issue number && exit 1

git log $branch -1 --format="%b"
echo "---"
echo ""
echo "### List of PRs for #$issue"
git print-issue-prs $issue $branch
