#!/bin/bash

set -e

JIRA_URL=${JIRA_URL:-https://scylladb.atlassian.net}

branch=$1
[[ -n $branch ]] && [[ -z $(git branch | cut -b 3- | grep ^$branch$) ]] && echo git branch $branch does not exist && exit 1

issue=$(echo $branch | sed -e 's/^\([a-z]\+-[0-9]\+\)-.*$/\1/')
[[ -z $issue ]] && echo branch $branch does not contain an issue number && exit 1

body=$2
[[ -n $body ]] && cat $body | sed -z 's/\n\-\-\-\n\n### List of PRs for .*/\n/'
[[ -z $body ]] && git log $branch -$(git count-commits $branch) --format="%s%n%n%b---" && echo -e "\nReference: $issue"

echo "---"
echo ""
echo "### List of PRs for [${issue^^}]($JIRA_URL/browse/${issue^^})"
git ghj-print-issue-prs $issue $branch
